import type { Project } from './model'

export interface PrototypeHtmlOptions {
  /** Relative path to the bundled `preview-runtime.js` in the export package. */
  runtimeSrc?: string
  /** Inline output from scripts/build-preview.mjs for a literally single-file preview. */
  runtimeCode?: string
  title?: string
  lang?: string
}

const escapeHtml = (value: string): string => value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;')
const escapeJson = (value: unknown): string => JSON.stringify(value).replace(/</g, '\\u003c').replace(/>/g, '\\u003e').replace(/&/g, '\\u0026').replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029')
const safeRuntimeSrc = (value: string): string => /^(?:https?:\/\/|(?:\.\.?\/|\/)[^\s"'<>]+$)/i.test(value) ? value : 'preview-runtime.js'

const previewCss = `
*{box-sizing:border-box}
html,body{margin:0;min-width:0;min-height:100%;background:#0b0c0e;color:#f4f1e8}
body{font-family:"Segoe UI",Arial,sans-serif}
button,input,select,textarea{font:inherit}
button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible,[tabindex]:focus-visible{outline:2px solid #f5b847;outline-offset:2px}
#layer-preview{width:100%;min-height:100vh;overflow:auto}
` 

/**
 * Produce the HTML shell for the bundled Prototype renderer. No document
 * values are interpolated into markup: project data lives in an escaped JSON
 * script node and the runtime creates React/native controls from it.
 *
 * `runtimeCode` is useful for a one-file handoff. Package exports normally use
 * the adjacent `preview-runtime.js` generated by scripts/build-preview.mjs.
 */
export const buildPrototypeHtml = (project: Project, options: PrototypeHtmlOptions = {}): string => {
  const title = escapeHtml(options.title ?? project.name ?? 'Layer prototype')
  const lang = /^[a-z]{2,3}(?:-[A-Z]{2})?$/.test(options.lang ?? 'en') ? options.lang ?? 'en' : 'en'
  const safeProject = structuredClone(project)
  safeProject.providers = []
  safeProject.connections = []
  safeProject.skills = []
  safeProject.commands = []
  safeProject.versions = []
  safeProject.settings = { ...safeProject.settings, mainPrompt: '', visionPrompt: '' }
  const data = escapeJson(safeProject)
  const runtime = options.runtimeCode
    ? `<script>${options.runtimeCode.replace(/<\/script/gi, '<\\/script')}</script>`
    : `<script src="${escapeHtml(safeRuntimeSrc(options.runtimeSrc ?? 'preview-runtime.js'))}" defer></script>`
  return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>${previewCss}</style></head><body><div id="layer-preview" aria-label="${title}"></div><script type="application/json" id="layer-project">${data}</script><script>window.__LAYER_PROJECT__=JSON.parse(document.getElementById('layer-project').textContent||'{}');</script>${runtime}<script>window.addEventListener('error',function(event){if(event.target&&event.target.tagName==='SCRIPT'&&!window.LayerPreviewRuntime){var host=document.getElementById('layer-preview');if(host)host.textContent='Preview runtime unavailable. Include preview-runtime.js beside this file.'}},true);</script></body></html>`
}

export const prototypeRuntimePath = 'preview-runtime.js'
export const previewEntryPath = 'src/preview-entry.tsx'
